openapi: 3.0.0
info:
  version: 1.0.0
  title: Accountable Governance
  description: >-
    This is an OpenAPI Specification created by oas-wizard
    (https://github.com/pafmon/oas-wizard)  
  contact:
    name: PabloFM
    email: pablofm@us.es
    url: 'http://www.isa.us.es'
  license:
    name: MIT
    url: 'http://opensource.org/licenses/MIT'
paths:
  '/api/v1/initialize':
    post:
      description: Initialize network
      operationId: initialize
      responses:
        '200':
          description: Network initialized
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
  '/api/v1/setUp/{agreement}':
    post:
      operationId: setUpAgreement
      parameters:
        - name: agreement
          in: path
          required: true
          description: Agreement to set up.
          schema:
            type : string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/queries'
      responses:
        '200':
          description: Agreement Set up
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
  '/api/v1/guarantees/{guarantee}':
    get:
      description: Get guarantee state
      operationId: guarantee
      parameters:
        - name: guarantee
          in: path
          required: true
          description: Guarantee to get.
          schema:
            type : string
      responses:
        '200':
          description: Guarantee collected
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
components:
  schemas:
    errorModel:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    elementsID:
      type: string
    queries:
      type: object
      properties:
        guaranteeID:
          type: string
        collector:
          type: string